### ISSUE TITLE
CocoaPods 

### ISSUE THREAD

**Issue by BrunoMiguens** [hmlongco/Factory#11]
Are you planning in making the lib available using cocoapods?

**Comment by tobi404** [comment]
I would like to use cocoa pods as well

**Comment by Vyazovoy** [comment]
Unfortunately I can't migrate our projects to SPM right now so it would be great to have Cocoapods as an installation option. LMK if you don't have objections and I will make a PR.

**Comment by hmlongco** [comment]
1.2.8

Enjoy!

**Comment by Vyazovoy** [comment]
Thank you, @hmlongco! One small suggestion: you don't need `"Classes"` [here](https://github.com/hmlongco/Factory/blob/main/Factory.podspec#L9) and taking into account that you import only `Foundation` I don't think that you need [those](https://github.com/hmlongco/Factory/blob/main/Factory.podspec#L13) `UIKit/AppKit` frameworks in the podspec.
