### ISSUE TITLE
Concurrency-safe warnings when `strict-concurrency` is set to `complete`

### ISSUE THREAD

**Issue by JeroenBakker-wbd** [hmlongco/Factory#111]
Hey, thanks for making this library. I really like using this :smile:. Which is why I have a question related to strict-concurrency:

In preparation for Swift 6, we've enabled `strict-concurrency` to `complete` in our project. But then we noticed the `Container.shared` is not concurrency-safe due to it being mutable.

![concurrency](https://github.com/hmlongco/Factory/assets/129863980/80fd11ec-e885-4eb1-9d27-351638dd48e5)

Are there plans for making `Factory` concurrency safe for the compiler?

**Comment by hmlongco** [comment]
Under most cases Factory is concurrency safe as it does its own locking mechanisms for registrations and resolutions and caching. I need to see what has to change other than that, but there could be issues with statics that I'm not sure how to resolve at the moment.

**Comment by hmlongco** [comment]
I may need to consider a breaking change to Factory to do this properly. The definition of SharedContainer is...
```swift
public protocol SharedContainer: ManagedContainer {
    static var shared: Self { get }
}
```
But I may need to change that to...
```swift
public protocol SharedContainer: ManagedContainer {
    static var container: Self { get set }
}

extension SharedContainer {
    /// Defines a thread safe access mechanism to the shared container type.
    public static var shared: Self {
        get {
            defer { globalRecursiveLock.unlock() }
            globalRecursiveLock.lock()
            return container
        }
        set {
            defer { globalRecursiveLock.unlock() }
            globalRecursiveLock.lock()
            container = newValue
        }
    }
}
```
With access to the static shared container managed by access functions. From the outside it looks mostly the same, with the only issue occurring if people define their own container types.
```swift
public final class MyCustomContainer: SharedContainer {
    /// Define the default shared container.
    public static var container = MyCustomContainer() // NAME CHANGE NEEDED
    /// Define the container's manager.
    public var manager: ContainerManager = ContainerManager()
    /// Public initializer
    public init() {}
}
```
Any thoughts?
