### ISSUE TITLE
Can't mock`.cached` scope factory

### ISSUE THREAD

**Issue by tcassany** [hmlongco/Factory#114]
Hi,

For some reason I can't mock factory with `.cached` scope. Event if I register an new factory or use `onTest`, it still use the original one. 

Here is the setup in the app
```
import Foundation
import Factory

protocol Service {
    var name: String { get }
}

final class DefaulfService: Service {
    let name = "DefaulfService"
}

final class MockService: Service {
    let name = "MockService"
}

final class MyAppContainer: SharedContainer {
    static var shared = MyAppContainer()
    var manager = ContainerManager()

    var service: Factory<Service> {
        self { DefaulfService() }
            .cached
    }
}

final class MyViewModel {
    var name: String {
        MyAppContainer.shared.service().name
    }

}
```

Here are the tests
```
import XCTest
@testable import BILL

final class FactoryTests: XCTestCase {

    func testMock() {
        MyAppContainer.shared.manager.push()
        addTeardownBlock {
            MyAppContainer.shared.manager.pop()
        }

        MyAppContainer.shared.service.register {
            MockService()
        }

        let sut = MyViewModel()
        XCTAssertEqual(sut.name, "MockService")
    }

    func testMock2() {
        MyAppContainer.shared.manager.push()
        addTeardownBlock {
            MyAppContainer.shared.manager.pop()
        }

        MyAppContainer.shared.service.onTest {
            MockService()
        }

        let sut = MyViewModel()
        XCTAssertEqual(sut.name, "MockService")
    }
}
```

Both are failing because `sut.name` is `DefaulfService`. 

I looked at how Factory resolves the dependency and I found something weird. In `FactoryRegistration.resolve(with parameters: P)`,  I'm expecting `let found = options?.factoryForCurrentContext() as? TypedFactory<P,T>` to not be nil for the first test and `let found = manager.registrations[id] as? TypedFactory<P,T>`  to not be nil for the second test. But the cast is rejected as you can see in the screenshots

<img width="897" alt="Screenshot 2023-06-02 at 17 49 59" src="https://github.com/hmlongco/Factory/assets/124849331/91decd33-de4a-417e-8065-6afc8c6238da">
<img width="956" alt="Screenshot 2023-06-02 at 17 49 27" src="https://github.com/hmlongco/Factory/assets/124849331/6fdf1167-ad10-4d17-be49-6a36e9504cc9">

Of course it is working fine when I do similar tests for a package. It only happens when I do it to test the app.

**Comment by hmlongco** [comment]
Something else is going on. I added your classes and tests to FactoryDemo, renamed them due to conflicts, and then ran then.

<img width="644" alt="Screenshot 2023-06-03 at 11 46 32 AM" src="https://github.com/hmlongco/Factory/assets/709283/df8a290a-2e80-45f2-b215-1ae09bdcce15">

Did you link Factory to your unit test module? If so your test code may be talking to it's own version of Factory.

**Comment by hmlongco** [comment]
Breakpointed first test.

<img width="912" alt="Screenshot 2023-06-03 at 11 57 24 AM" src="https://github.com/hmlongco/Factory/assets/709283/d04fb43e-10cb-4a4c-895a-257bda668862">

**Comment by hmlongco** [comment]
Also tested in a cocoa pod project.

**Comment by hmlongco** [comment]
I did find an issue where registering a new context didn't clear the existing cache. Clearing the cache was expected behavior for register.

See develop.

**Comment by tcassany** [comment]
Sorry I was busy last week. I think that due to a weird configuration in our project
Thanks for the help.
