### ISSUE TITLE
Equivalent of Resolver implement for multiple protocol

### ISSUE THREAD

**Issue by hyazel** [hmlongco/Factory#115]
Hello,

I'm currently migrating my code base from `Resolver` to `Factory`.

I have some registrations that use the same instance for multiple protocols like this : 

```
main.register { XYZCombinedService() }
    .implements(XYZFetching.self)
    .implements(XYZUpdating.self)
```

What would be the equivalent for `Factory` ?

Thanks a lot !

**Comment by hmlongco** [comment]
Since they work differently, there's not a direct equivalent. Just make two factories.
```swift
    var xyzFetching: Factory<XYZFetching> { self { XYZCombinedService() } }
    var xyzUpdating: Factory<XYZUpdating> { self { XYZCombinedService() } }
```
Or, if you prefer
```swift
    var xyzFetching: Factory<XYZFetching> { self { self.xyzCombined() } }
    var xyzUpdating: Factory<XYZUpdating> { self { self.xyzCombined() } }
    private var xyzCombined: Factory<XYZCombinedService> { self { XYZCombinedService() } }
```
I'd use the later version if the combined service needs to be cached.
