### ISSUE TITLE
Support @Observable macro 

### ISSUE THREAD

**Issue by emadhegab** [hmlongco/Factory#120]
in a model where i use @Observable macro , 
```swift
@Observable
class SplashScreenViewModel {
    var presented: Bool = false

    @Injected(\.loginService) private var loginService: LoginServicing

```

i get 2 errors at the Injected vars 

> @Observable requires property 'loginService' to have an initial value (from macro 'Observable')
> Property wrapper cannot be applied to a computed property

**Comment by hmlongco** [comment]
This is an issue with @Observable. 

"In the current implementation, the @Observable macro requires that all stored properties have a default value. This helps observable types rely on definitive initialization, use the implicitly generated initializers, and define additional initializers in extensions."

You can, however, get past the issue by doing something like...
```swift
    @ObservationIgnored @Injected(\.myServiceType) private var service
```

Also keep in mind that if you use @Observable your application can only run on iOS 17 and higher.

See: https://developer.apple.com/documentation/swiftui/migrating-from-the-observable-object-protocol-to-the-observable-macro

**Comment by joeljfischer** [comment]
I did figure this out, even before seeing this, but I'm seeing a new issue that I wasn't having with `ObservableObject`. My SwiftUI previews where I inject a preview object like:

```swift
let _ = Container.shared.weatherManager.register { WeatherManagerPreview() }
```

is no longer working. In all my previews, I now get errors because they are running the Impl objects in my `ViewModel`s instead of the preview objects I'm registering. This doesn't happen if I switch back to `ObservableObject` (which I _really_ don't want to do because of the performance benefits to `@Observable`)

**Comment by hmlongco** [comment]
I think your problem is elsewhere, as the following works...
```swift
import Factory
#if canImport(Observation)
import Observation
#endif
import SwiftUI

@available(iOS 17, *)
protocol ObservationServiceType: AnyObject {
    var name: String { get set }
}

@available(iOS 17, *)
@Observable
class ObservationService: ObservationServiceType {
    var name: String = "ObservationService"
}

@available(iOS 17, *)
@Observable
class MockObservationService: ObservationServiceType {
    var name: String = "MockObservationService"
}

@available(iOS 17, *)
extension Container {
    var observableService: Factory<ObservationServiceType> {
        self { ObservationService() }
    }
}

@available(iOS 17, *)
struct ObservableView: View {
    @Injected(\.observableService) var observableService
    var body: some View {
        HStack {
            Text(observableService.name)
            Spacer()
            Button("Mutate") {
                observableService.name += " *"
            }
        }
        .padding()
    }
}

@available(iOS 17, *)
#Preview {
    let _ = Container.shared.observableService.register { MockObservationService() }
    return ObservableView()
}
```

**Comment by joeljfischer** [comment]
Okay, I tested this myself, and you're correct, it works. I have no idea why my previews are now using the default Impl versions and not preview versions of my services, but it doesn't appear to be what I thought it was.

**Comment by cneuwirt** [comment]
Are there any plans to support @Bindable with @Injected wrapper so bindings are available for use in Publisher Combinators

[Initial comment](https://github.com/hmlongco/Factory/issues/175)
