### ISSUE TITLE
Crash due to concurrent access to cache

### ISSUE THREAD

**Issue by danielepantaleone** [hmlongco/Factory#122]
Hi,

We are experiencing some crashes due to simultaneous access to Factory Scope.Cache:

<img width="980" alt="Screenshot 2023-06-20 at 13 09 29" src="https://github.com/hmlongco/Factory/assets/1245124/cf9b1841-64e8-4f56-83c7-378a398d4416">
<img width="847" alt="Screenshot 2023-06-20 at 13 10 22" src="https://github.com/hmlongco/Factory/assets/1245124/285ca179-43d9-422b-8a05-1421292703b5">

We traced down the a piece of code in which we access a `@WeakLazyInjected` wrapped service inside the class deinit (if we comment it, we don't experience the crash):

```swift

class MyClass {
    
    @WeakLazyInjected(\MyContainer.myService)
    private (set) var myService

    deinit {
        myService?.doSomething() // <-- Thread 1: Simultaneous accesses to 0x600003720330, but modification requires exclusive access
    }
}
```

Digging a bit in Factory code I managed to see that every access is protected by a mutex, so I can't explain why this is happening.

**Comment by danielepantaleone** [comment]
Or maybe we can just refactor our code not to perform operations inside deinit (which I don't like very much). We actually moved that piece of code out of deinit at the moment, but it was worth reporting the issue. Maybe someone else will stumble on this very same problem.

**Comment by hmlongco** [comment]
Still may add the myService.initialized flags as doing any kind of cleanup of that nature will resolve the instance, even if the instance was never resolved previously.

Or maybe $myService.optional?.doSomething()

Hmmm. Needs a better name.

**Comment by danielepantaleone** [comment]
I like the second the most. Maybe something like:

$myService.resolvedOrNil?.doSomething()

Something that suggests that resolution is not going to be performed in this specific case. I'm not very good at naming things 😅

**Comment by hmlongco** [comment]
Sounds good to me. See develop branch.

**Comment by danielepantaleone** [comment]
I just tried and it works perfectly 👍🏻
