### ISSUE TITLE
Unable to integrate Factory via CocoaPods on Xcode 14.3.1 (14E300c)

### ISSUE THREAD

**Issue by minhnimble** [hmlongco/Factory#123]
I encountered the following issue when integrating the Factory lib into my iOS project:

```
Failed to build module 'Factory'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)'). Please select a toolchain that matches the SDK.
```

![Screenshot 2023-06-22 at 13 33 40 copy](https://github.com/hmlongco/Factory/assets/70877098/32f929c0-a977-4e6c-a4d6-6043bf46e918)

I have this issue integrating the latest Factory lib (version `2.1.5`) via CocoaPods into my project, and my Xcode version is `14.3.1`. When building the application on Xcode `14.2`, everything works fine. Any help would be greatly appreciated 🙏

![Screenshot 2023-06-22 at 14 35 16](https://github.com/hmlongco/Factory/assets/70877098/92f3e3b0-2894-4df7-b927-29b71f6bdb8c)

P/S: A potential solution is that the Factory lib needs to set the following flag to `YES`:
`BUILD_LIBRARY_FOR_DISTRIBUTION = YES;`
Ref: https://stackoverflow.com/a/58656323

**Comment by danielepantaleone** [comment]
Factory is distributed as source and not as a compiled XCFramework, so there is not place (and need) to set `BUILD_LIBRARY_FOR_DISTRIBUTION=YES`.

Did you try to:

- Close Xcode
- Delete derived data
- Remove your Podfile.lock and the Pods directory
- run `pod cache clean 'Factory' --all`
- run `pod install`

**Comment by minhnimble** [comment]
@danielepantaleone thanks for your reply, it now is realized that in the Podfile's config of my project, the lib is being built in the binary form `, :binary => true`. Removing this setting now will remove this SDK issue.

Thank you again for your support, marking this issue as `Closed` now 🙏
