### ISSUE TITLE
Overriding registration in preview

### ISSUE THREAD

**Issue by hyazel** [hmlongco/Factory#132]
Hello,

I register a `service` like this : 

```
var collectionService: Factory<CollectionServiceContract> {
        self { CollectionService() }
            .onPreview {
                CollectionServiceMock(items: collectionMock1)
            }
    }
```

My purpose is to have a `CollectionServiceMock` for previews that use `collectionMock1` in most of my views.

But sometimes I'd like to use an another mock than `collectionMock1`. 

In my preview I tried to do something like this : 

```
 static var previews: some View {
        _ = ServiceContainer.shared.collectionService.register { CollectionServiceMock(items: collectionMock2) }

       return MyView()
}
```

But doesn't seem to use the `collectionMock2` instead of the `collectionMock1`. 

My question is : How do you switch your mock during previews ?

**Comment by hmlongco** [comment]
See the section "The Factory Wins" in the documentation on Factory Modifiers.

https://hmlongco.github.io/Factory/documentation/factory/modifiers

**Comment by hyazel** [comment]
Thanks !

**Comment by hmlongco** [comment]
Once just adds a small bit of processing to the resolution process, so you can use it as much as you like. That said, I'd only use it for scenarios where you're trying to override one of the contexts and you put those context modifiers inside of the Factory. It makes no sense to have it for plain or scoped factories.

Don't forget the auto registering option.
