### ISSUE TITLE
Promised ParameterFactory

### ISSUE THREAD

**Issue by windom** [hmlongco/Factory#133]
Hi! Is there any reason for not having `promised()` sugar for `ParameterFactory` just as for `Factory`? I think it would be just as useful.

Tiny bug: `Globals.resetAndTriggerFatalError` is not forwarding the `file` and `line` parameters to `triggerFatalError`.

(Also wanted to say, this framework really rocks, thank you!)

**Comment by hmlongco** [comment]
At one point I was keeping code size down but not sure that's good justification. Coming in 2.2.1.
