### ISSUE TITLE
Could not find module 'Factory' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at

### ISSUE THREAD

**Issue by skywalkerlw** [hmlongco/Factory#134]
I'm on Xcode 14.3 and Apple M1 chip chip with latest Factory Swift Package

Got this error

![image](https://github.com/hmlongco/Factory/assets/2090084/93f9c34d-233c-4ae0-972f-139d05951223)

Seem an issue only for Apple M1 chip according to this: https://stackoverflow.com/questions/56957632/could-not-find-module-for-target-x86-64-apple-ios-simulator.

**Comment by hmlongco** [comment]
That's not an issue with Factory, but with how you're importing and building Factory and other third party libraries in your project.

See: https://developer.apple.com/documentation/technotes/tn3117-resolving-build-errors-for-apple-silicon/
