### ISSUE TITLE
MainActor issue with ObservableObject's

### ISSUE THREAD

**Issue by cabyambo** [hmlongco/Factory#135]
I am getting an error when trying to register an `ObservableObject` marked with `@MainActor`
```
Call to main actor-isolated initializer 'init()' in a synchronous nonisolated context
```

Here's how I am registering the object:
```
extension Container {
    var homeViewModel: Factory<HomeViewModel> {
        self { HomeViewModel() }
    }
}
```

And here is the object itself:
```
import Foundation
import Factory
import Combine

@MainActor // Removing this fixes the error, but I need this
class HomeViewModel: ObservableObject {
    @Injected(\.cardImageUrlRepository) private var cardImageUrlRepository
   
    @Published private(set) var cardImageUrls: [String] = []
    
    init() {
        fetchCreditCardImageUrls()
    }
    
    private func fetchCreditCardImageUrls() {
        Task {
            // Fetch data using repository
            // Set cardImageUrls to fetched data
        }
    }
}
```

Is it possible to keep the `@MainActor` tag?

**Comment by hmlongco** [comment]
If you mark the entire class that way then you need to mark the initializer as nonisolated in order to get around that.

I tend to prefer marking async functions as @MainActor as needed, and not the entire class. I wrote a lot about that on Medium: https://betterprogramming.pub/async-await-and-mainactor-strategies-cc35b6c58b52

**Comment by jubishop** [comment]
just came across this, you can also do this I believe:

```swift
extension Container {
    var homeViewModel: Factory<HomeViewModel> {
        self { @MainActor in HomeViewModel() }
    }
}
```

**Comment by jubishop** [comment]
I take it back, that doesn't work.  see https://github.com/hmlongco/Factory/issues/211 for a good answer.

**Comment by hmlongco** [comment]
```swift
extension Container {
  @MainActor
  var mainActorType: Factory<MainActorType> {
      self { @MainActor in SomeMainActorType() }
  }
}
```

**Comment by jubishop** [comment]
yeah this is what i've been doing.  if you want access from a class not on the main actor (or whatever global actor your factory is on), you can't use the @Injected macros, tho.  so I've taken to doing (using the same types as your example above):

```swift
var mainActorType: MainActorType { get async { await Container.shared.mainActorType() } }
```

**Comment by DmitryKhristenko** [comment]
> > ```
> > extension Container {
> >   @MainActor
> >   var mainActorType: Factory<MainActorType> {
> >       self { @MainActor in SomeMainActorType() }
> >   }
> > }
> > ```
> 
> This solution does not work in Swift 6 mode (in my use case, I'm trying to inject WKProcessPool, so I can't remove `@MainActor` either):
> 
> ```
> Converting function value of type '@MainActor @Sendable () -> WKProcessPool' to '@Sendable () -> WKProcessPool' loses global actor 'MainActor'
> ```

Same problem

**Comment by hmlongco** [comment]
First, the develop branch has changes for 6.2.

Second, in develop you no longer need the internal MainActor.

```swift
extension Container {
  @MainActor
  var mainActorType: Factory<MainActorType> {
      self { SomeMainActorType() }
  }
}
```
