### ISSUE TITLE
Tiny bug: promised is not forwarding the file and line parameters to triggerFatalError.

### ISSUE THREAD

**Issue by novr** [hmlongco/Factory#142]
resetAndTriggerFatalError's file and line parameters not working 

- #133

**Comment by hmlongco** [comment]
Think I fixed that in 2.2.1, but never pushed it. 2.3.0 will be available shortly. Should cover it.

**Comment by sebastian-qm** [comment]
Hi Michael (@hmlongco), 
unfortunately, this was never merged. 😢 
Can you please reopen this issue? 🙏
