### ISSUE TITLE
@InjectedLazyObject

### ISSUE THREAD

**Issue by lyzkov** [hmlongco/Factory#149]
I have failed to create an `@InjectedLazyObject` property wrapper that could resolve dependency upon access to `wrappedValue` or `projectedValue.` Is there any hope that it is possible? Could `ObservedObject<DependencyType>` be created by Factory and injected with `@LazyInjected`?

**Comment by hmlongco** [comment]
Nope. Property wrappers are structs. To do lazy property wrappers you have to mutate the struct value. And you can't mutate an "observable object" property wrapper installed on a View.

I provided an InjectedObject wrapper for Factory, but at some point I'm probably going to mark it as deprecated, especially with the advent of @Observable in iOS 17.

Best to stick with @StateObject and inject needed dependencies into the view model when needed.
