### ISSUE TITLE
2.3 no longer works on linux - missing os_unfair_lock

### ISSUE THREAD

**Issue by doozMen** [hmlongco/Factory#152]
Will try to find a workaround but would appreciate help. Ik tested 2.3 from develop only on the mac I'm afraid.

**Comment by hmlongco** [comment]
Minor revision, but PR merged. No pod or release tag yet.

**Comment by hmlongco** [comment]
If you can pull main and let me know if it's working for you before I try to do a release.

**Comment by hmlongco** [comment]
2.3.1 published
