### ISSUE TITLE
Cannot build XCFramework

### ISSUE THREAD

**Issue by danielepantaleone** [hmlongco/Factory#159]
Hi, we are using Factory as dependency in a library we are shipping as compiled XCFramework. We are experiencing an issue during the build of the XCFramework when using Factory 2.3

`The following build commands failed:
	CompileSwift normal arm64 (in target 'Factory' from project 'Pods')
	SwiftCompile normal arm64 Compiling\ Aliases.swift,\ Containers.swift,\ Contexts.swift,\ Factory.swift,\ Globals.swift,\ Injections.swift,\ Key.swift,\ Locking.swift,\ Modifiers.swift,\ Registrations.swift,\ Resolutions.swift,\ Resolver.swift,\ Scopes.swift /Users/vagrant/git/Pods/Factory/Sources/Factory/Factory/Aliases.swift /Users/vagrant/git/Pods/Factory/Sources/Factory/Factory/Containers.swift /Users/vagrant/git/Pods/Factory/Sources/Factory/Factory/Contexts.swift /Users/vagrant/git/Pods/Factory/Sources/Factory/Factory/Factory.swift /Users/vagrant/git/Pods/Factory/Sources/Factory/Factory/Globals.swift /Users/vagrant/git/Pods/Factory/Sources/Factory/Factory/Injections.swift /Users/vagrant/git/Pods/Factory/Sources/Factory/Factory/Key.swift /Users/vagrant/git/Pods/Factory/Sources/Factory/Factory/Locking.swift /Users/vagrant/git/Pods/Factory/Sources/Factory/Factory/Modifiers.swift /Users/vagrant/git/Pods/Factory/Sources/Factory/Factory/Registrations.swift /Users/vagrant/git/Pods/Factory/Sources/Factory/Factory/Resolutions.swift /Users/vagrant/git/Pods/Factory/Sources/Factory/Factory/Resolver.swift /Users/vagrant/git/Pods/Factory/Sources/Factory/Factory/Scopes.swift (in target 'Factory' from project 'Pods')
(2 failures)`

We are using Xcode 15 and iOS 12 as deployment target.
Everything works fine on Factory 2.2

**Comment by hmlongco** [comment]
There were some path changes and the minimum iOS version went to 12, but nothing else of significance changed in the podspec. try pod install --repo-update
