### ISSUE TITLE
Are you interested for macro ?

### ISSUE THREAD

**Issue by bourvill** [hmlongco/Factory#162]
Hello, would you be interested in adding macros to your project?

We like your project and use `SharedContainer` a lot to separate our domains.

The macro available [here](https://github.com/district-web/FactoryMacro) helps reduce frequently repeated code.

The code is tested, some things may still be missing, but would you be interested in porting it to your repository?

**Comment by hmlongco** [comment]
Interesting, would have to think about it. Should note, however, that FactoryContainer is an existing typealias for Container.

**Comment by hmlongco** [comment]
Probably not at this point in time. I am considering macros for other functionality in the future.

**Comment by markst** [comment]
Sorry to resurrect an old issue but thought best to avoid creating a new issue.

@hmlongco I wonder if two years on whether you might reconsider [Macro](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/macros/)'s in order to define dependencies?


```swift
@Provides
public class MyService: MyServiceType {
    public let id = UUID()
}
```

**Comment by markst** [comment]
@bourvill interesting; I'd be curious to investigate how some of these libraries do it
https://github.com/dfed/SafeDI
https://github.com/rockname/sword
https://github.com/uber/needle
