### ISSUE TITLE
Can not build app for deivce ios 15 when import Factory

### ISSUE THREAD

**Issue by toaindt-3169** [hmlongco/Factory#163]
When I used Factory in my SwiftUI project, it failed to build on devices running iOS 14 and iOS 15.
Very pleased with your response!

**Comment by toaindt-3169** [comment]
Home screen only white background.

**Comment by hmlongco** [comment]
Haven't had any issues building to device, nor any other reports of such. Not enough information here to debug issue.

**Comment by toaindt-3169** [comment]
Your demo application. When I build them on iOS 15, the screen is white and the app doesn't run. This is the same when I first installed Factory using SPM and my configuration was as follows:

var sessionManager: Factory<URLSessionManager> {
          return self { BaseSessionManager(base: self.baseUrl, session: self.urlSession())
                  .set(decoder: JSONDecoding())
                  .set(encoder: JSONEncode())
                  .interceptor(URLRequestInterceptorHeaders([
                      "Authorization": self.authorization()
                  ]))
          }.singleton
      }
    
      var private urlSession: Factory<URLSession> {
          let configuration = URLSessionConfiguration.default
          config.timeoutIntervalForRequest = Const.timeout
          config.timeoutIntervalForResource = Const.timeout
          return self { URLSession(configuration: config) }.singleton
      }
    
      private var baseUrl: URL? {
          return URL(string: APIService.Urls.baseUrl)
      }
    
      private function delegate() -> String {
          let username = APIService.Authorization.username
          let password = APIService.Authorization.password
          let credential = Data("\(username):\(password)".utf8).base64EncodedString()
          returns "Basic\(credentials)"
      }
Can you please give me the configuration when running the application without experiencing the same phenomenon as mine?

**Comment by hmlongco** [comment]
I'd pushed a project change up earlier today as the demo app didn't have the common framework as part of its included libraries.

**Comment by toaindt-3169** [comment]
Thank you for your feedback. Currently, your demo app can be built on iOS 15. But I am using your RequestBuilder library to build the base networking. However, currently my app still cannot be built to iOS 14 -  15, and on iOS 16 and above, my app still runs normally. This situation is similar to your demo app before fixing, CPU is always 100% and no UI is displayed. Currently I still can't fix it. 
I hope you can help me fix the error of not being able to build on iOS 14 - 15. 
Thank you very much !

**Comment by toaindt-3169** [comment]
Thank you so much!
