### ISSUE TITLE
Privacy manifest file

### ISSUE THREAD

**Issue by danielepantaleone** [hmlongco/Factory#177]
Starting from Spring 2024 Apple requires apps and third party SDKs to include a Privacy manifest file. Would it be possible to include it in the next release of Factory?

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by hmlongco** [comment]
yes

**Comment by hmlongco** [comment]
Or not. Without spending a ton of time on this. I can provide a file... that's empty. Factory doesn't track any user info, data, position data, or other PII.

Anyone know of what to do in this situation?

**Comment by danielepantaleone** [comment]
I believe your should add a `PrivacyInfo.xcprivacy` file with just `NSPrivacyTracking` set to `false`.
