### ISSUE TITLE
Xcode compile error in `FactoryKey.init(type:key:)` due to use of @inlinable

### ISSUE THREAD

**Issue by FKREISE** [hmlongco/Factory#184]
Using Factory version 2.3.1 and Xcode 15.2. produces a compiler error.
Cause of the error is probably the use of the build setting `"BUILD_LIBRARY_FOR_DISTRIBUTION"`.

<img width="1166" alt="Screenshot 2024-02-05 at 7 03 21 PM" src="https://github.com/hmlongco/Factory/assets/127393870/91f3cea7-5e5d-4e29-885c-92740e662dcf">

It might be related to the use of `@inlinable`, see this discussion: https://github.com/grpc/grpc-swift/issues/1063#issuecomment-785727051

**Comment by hmlongco** [comment]
Updated converting key to an internal type. Please try branch again.

**Comment by hmlongco** [comment]
Inlines removed and key internal in 2.3.2
