### ISSUE TITLE
Release for Privacy manifest and iOS 15

### ISSUE THREAD

**Issue by havebeenfitz** [hmlongco/Factory#189]
Hi, I saw [this](https://github.com/hmlongco/Factory/issues/177) issue and a privacy manifest already in main branch. But Is it maybe possible to "cherry pick" this privacy manifest commit and release a new version while still supporting iOS 15?) This privacy thing should roll out in spring and there could be some issues with App Store review for us.

I see that iOS 15 support is dropped in main

**Comment by havebeenfitz** [comment]
Well actually I'm not completely sure it's needed according to [this](https://developer.apple.com/support/third-party-SDK-requirements/) doc. There's a list of sdks and Factory is not in that list

**Comment by hmlongco** [comment]
"This functionality is a step forward for all apps, and we encourage all SDKs to adopt it to better support the apps that depend on them."

**Comment by danielepantaleone** [comment]
> Hi, I saw [this](https://github.com/hmlongco/Factory/issues/177) issue and a privacy manifest already in main branch. But Is it maybe possible to "cherry pick" this privacy manifest commit and release a new version while still supporting iOS 15?) This privacy thing should roll out in spring and there could be some issues with App Store review for us.
> 
> I see that iOS 15 support is dropped in main

I don't see support for iOS 15 being dropped in main branch. Maybe I'm missing something though 😁

**Comment by hmlongco** [comment]
2.3.2 added manifest
