### ISSUE TITLE
Sendable conformance for `Container`

### ISSUE THREAD

**Issue by erichoracek** [hmlongco/Factory#190]
With Swift 5.10 released and Swift 6 on the horizon, consumers of Factory would expect `Container` to conform to `Sendable` as it is intended to be thread safe. However, since it contains a property of `containerManager`, it's not possible to mark it as such:

<img width="997" alt="image" src="https://github.com/hmlongco/Factory/assets/438313/c54b63fd-e1bf-418e-8e56-544e3355b113">

Furthermore, when you attempt to conform `ContainerManger` to sendable, you notice that it has publicly writable properties that are not protected, namely `defaultScope` but also some other debug ones, so it cannot conform to `Sendable` either:

<img width="997" alt="image" src="https://github.com/hmlongco/Factory/assets/438313/e17abeae-c0cc-4131-a395-f8e920f0d9e6">

To satisfy the `Sendable` contract, ideally `Container` and `ContainerManager` would both have `Sendable` conformances, though this might require an API rethink.

**Comment by hmlongco** [comment]
Most of Factory is locked and already thread-safe, so adding complete sendable conformance shouldn't be that difficult.

**Comment by emadhegab** [comment]
is there any intension to fix this?

**Comment by NachoSoto** [comment]
I just sent #209 so at least `Factory` doesn't fail to compile with Swift 6.

**Comment by hmlongco** [comment]
See the Swift6 branch. That's Sendable and compatible with Swift concurrency.
