### ISSUE TITLE
Replace resolver with the factory pacakge but my app architure is modular

### ISSUE THREAD

**Issue by EngOmarElsayed** [hmlongco/Factory#195]
Today, I have been trying to replace resolver with the factory pacakge but my app architure is modular and when I create a property inside an extension for the container and then go to another package in the app to use this instance, it doesn’t find any of the property’s I created. I created the property in a global file.

Did I miss something ?

Resolve files are the one’s that containes the extension of the container that contains the computed property’s

<img width="232" alt="Screenshot 2024-03-25 at 7 23 51?AM" src="https://github.com/hmlongco/Factory/assets/125718818/0135074e-2fc4-4e66-81ea-e4d8812130b7">

**Comment by SaidAlSouti** [comment]
I am struggling with the same problem here. My app is also modular and it follows Clean Architecture. So the domain layer (use cases) does not know the implmentation (doe snot impot data layer modules) so how can we resolve the data layer service as a protocol.

**Comment by SaidAlSouti** [comment]
Any update on this??

**Comment by EngOmarElsayed** [comment]
I think you should use Resolver insted it works

**Comment by SaidAlSouti** [comment]
I did return to Resolver package, which is archived. 
We raised this issue so the maintainers will be aware off.

**Comment by otnielyehezkiel** [comment]
@SaidAlSouti @EngOmarElsayed can you share your solution after migrating from resolver?

**Comment by SaidAlSouti** [comment]
> @SaidAlSouti @EngOmarElsayed can you share your solution after migrating from resolver?

Dear @otnielyehezkiel I kept using Resolver.

**Comment by hmlongco** [comment]
Resolver is deprecated. No support for new versions of Xcode. No support for actors, sendable, or Swift concurrency. zip.
