### ISSUE TITLE
typealias with 2 protocols leads to EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by dsuresh-ap** [hmlongco/Factory#197]
I have the following code:
```
protocol DataSource<Model>
protocol DataSyncSource<Model>
typealias CloudDataSyncSource<Modal> = DataSource<Modal> & DataSyncSource<Modal>
```

My injection:
```
var conversationCloudDataSyncSource: Factory<any CloudDataSyncSource<ConversationModal>> {
        self { ConversationFirebaseDataSource() }.cached
    }
```
`@Injected(\DataContainer.conversationCloudDataSyncSource) private var cloudMessageDataSyncSource`

However I get `EXC_BAD_ACCESS (code=2` on access of the `DataSyncSource` methods  if I set the typealias (`CloudDataSyncSource`) as the registration type. If I specify the type as `DataSyncSource` then access is fine. Any ideas?

**Comment by hmlongco** [comment]
Was looking to see if this was an issue in Swift 6/Xcode 16, but code doesn't compile. Need working code subset that compiles, please.
