### ISSUE TITLE
[Question] - Migration from Resolver

### ISSUE THREAD

**Issue by alexanderwe** [hmlongco/Factory#2]
Hi Michael, 

great to see another dependency injection library from you. I am a long time `Resolver` user and now questioning myself if it is possible to migrate from `Resolver` to `Factory` and how. I hope it is fine to ask some question about this in this format. 

Currently Resolver is used in a MicroFeature architecture. So I have a lot of distinct features, all with an interface target and an implementation target. These features then are getting packed together in the final application target. 

Each feature implementation only knows the interface of other features AND the Resolver framework. The application target in the end knows each features interface and each features implementation and registers appropriate implementations to the interfaces for other features to consume. 

**Some Code examples below.** 
Feature A
```swift
// FeatureA interface

protocol FeatureAInterface {
    func fetchResourceA() async -> ResourceA
}
```

```swift
// FeatureA implementation

protocol FeatureAImplementation: FeatureAInterface {
    func fetchResourceA() async -> ResourceA {
        return ResourceA()
    }
}
```

Feature B
```swift
// FeatureB interface

protocol FeatureBInterface {
    func fetchResourceB() async -> ResourceB
}
```

```swift
// FeatureB implementation

final class FeatureBImplementation: FeatureBInterface {
    
    @Injected private var featureA: FeatureAInterface   
    
    func fetchResourceB() async -> ResourceA {
        let a = await featureA.fetchResourceA() 
        return ResourceB()
    }
}
```

App

```swift
import FeatureA
import FeatureAInterface

import FeatureB
import FeatureBInterface

register { FeatureAImplementation() }
    .implements(FeatureAInterface.self)

register { FeatureBImplementation() }
    .implements(FeatureBInterface.self)
```

When I now look at `Factory` I saw that it is now required to create an extension on `Container` to make services explicitly type safe available to consumers. Maybe I misunderstood the new library a little bit, but do you have some suggestion of how the behaviour I described will be working with `Factory` ? What I want to avoid is to expose the implementation of features to other features. Exposing implementations inside the place where everything is registered is fine though.

Maybe another question - will it also be possible to have a `@OptionalInjected` functionality again ? Maybe I oversaw it. 

Thanks a lot in advance, and again thanks a lot for all your work so far !

**Comment by hmlongco** [comment]
That one's tough. 

What you're currently doing is what Resolver does. Basically the code is hoping that someone, somewhere, has registered a factory to provide an instance of the needed interface. 

Factory, on the other hand, works by ensuring that there's an implementation to be seen, hence it's compile-time safe. It doesn't hope. It knows.

I'll have to think about that one a bit.

**Comment by alexanderwe** [comment]
Thanks a lot for thinking about it. I was also wondering if the approach described by me will even be possible with `Factory`. Because it is exactly what you said. 
The features just rely on, that there will be some implementation conforming to the given protocol. They have no guarantee however and the application will crash if a developer has forgotten to add a certain dependency.

**Comment by hmlongco** [comment]
Still thinking, but one option might be something like this...
```swift
protocol FeatureAInterface {
    ...
}
extension Container {
    static var featureA = Factory<FeatureAInterface?> { nil }
}
```
Which allows...
```swift
import FeatureA
...
class FeatureBImplementation: FeatureBInterface {
    private var featureA = Container.featureA()
    func fetchResourceB() async -> ResourceB {
        let _ = await featureA?.fetchResourceA()
        return ResourceB()
    }
}
```
Then at app launch you call setup...
```swift
func setup() {
    Container.featureA.register { FeatureAImplementation() }
    Container.featureB.register { FeatureBImplementation() }
}
```
Each interface publishes an optional Factory that returns nil so it doesn't expose implementation. Anyone who uses it has to handle optional aspect, but no crash if not provided. Setup function on app registers implementations and wires the world together, much as you did before.

**Comment by hmlongco** [comment]
Oh, and note 
```swift

class FeatureBImplementation: FeatureBInterface {

   @Injected(Container.featureA) private var featureA

    func fetchResourceB() async -> ResourceB {
        let _ = await featureA?.fetchResourceA()
        return ResourceB()
    }
}
```
If the type of the factory is optional, then the type @Injected is optional. No need for OptionalInjected.

**Comment by alexanderwe** [comment]
Very interesting, thanks a lot for providing the suggestions. This means, that, in the context of the example: `FeatureB` then needs to validate that necessary injected types are not nil, right ? So basically what previously was done by `Resolver` internally, now needs to be done by the different `Feature` implementations. 

So the general idea high level idea would be: 
In the `Interface` we provide a "cutout" for the injected service, but set it to nil. Inside the app we fill it out with the correct implementation. 

I need to think a little bit about it - I quite liked this "dynamic" approach of `Resolver` - or better said, the "implicit unwrapped optional" approach. But with your suggestions, I think, I could atleast keep the base functionality.

Also very nice, that `@OptionalInjected` is not needed any longer :)

**Comment by alexanderwe** [comment]
But I think compile time safety is definitely a very nice approach ! Great to see this improvement :) So really good work.

**Comment by hmlongco** [comment]
I mean, there's nothing stopping you from explicitly unwrapping it on your own...
```swift
class FeatureBImplementation: FeatureBInterface {

    @Injected(Container.featureA) private var featureA: FeatureAInterface!

    func fetchResourceB() async -> ResourceB {
        let _ = await featureA.fetchResourceA()
        return ResourceB()
    }
}
```
Other than losing the main benefit of Factory, this is. ;)

I'll still noodle on this. Let me know if you come up with something.

**Comment by hmlongco** [comment]
Another conversation on this is occurring in [issue 3](https://github.com/hmlongco/Factory/issues/3).

**Comment by alexanderwe** [comment]
@hmlongco Thanks a lot for linking the other issue !
