### ISSUE TITLE
Canvas Preview Mock Override Requires Play Button

### ISSUE THREAD

**Issue by scottymack** [hmlongco/Factory#20]
Thanks for your excellent work here Michael!  I'm a fan of Resolver and an even bigger fan of Factory.

When looking at the `FactoryDemo` project `ContentView` preview, I don't see the `MockService2` override actually taking effect until I click the canvas play button. Is there a way to work around this, or is this the expected behavior?

![image](https://user-images.githubusercontent.com/14916442/188703889-646ef7c2-0f79-4c5d-be05-2707f60976b3.png)

![image](https://user-images.githubusercontent.com/14916442/188703943-10b47e38-f6b5-4606-ae40-7a13524f807b.png)

It would be awesome to have multiple previews with different mocked data similar to the code below and see the differences without having to click the play button on each. Is this possible with Factory?

```
struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        Group {
            let _ = Container.myServiceType.register { MyService() }
            ContentView()
            
            let _ = Container.myServiceType.register { MockService2() }
            ContentView()
        }
    }
}
```

This question was inspired by your article where you demonstrated previewing the different states of the `AccountListView` with a different loader:

```
struct AccountListView_Previews: PreviewProvider {
  static var previews: some View {
    Group {
      let vm2 = AccountListViewModel(loader: MockTwoAccounts())
      AccountListView(viewModel: vm2)
            
      let vm0 = AccountListViewModel(loader: MockNoAccounts())
      AccountListView(viewModel: vm0)
            
      let vme = AccountListViewModel(loader: MockAccountsError())
      AccountListView(viewModel: vme)
    }
  }
}
```

**Comment by hmlongco** [comment]
From the demo app...

```swift
struct ContentView: View {
    @StateObject var model = ContentModuleViewModel()
    var body: some View {
        VStack(spacing: 20) {
            Text(model.text() + " for \(model.name)")
        }
        .padding()
    }
    
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        Group {
            let _ = Container.myServiceType.register { MockServiceN(4) }
            let model1 = ContentModuleViewModel()
            ContentView(model: model1)

            let _ = Container.myServiceType.register { MockServiceN(8) }
            let model2 = ContentModuleViewModel()
            ContentView(model: model2)
        }
    }
}
```
When running in Xcode 14 you see 4 in the first view and 8 in the second. Secret is constructing the models inline instead of waiting for view body instantiation to resolve the thunked view models.
