### ISSUE TITLE
SwiftUI previews with multiple modules

### ISSUE THREAD

**Issue by callo90** [hmlongco/Factory#200]
Hello,

I've been facing problems with the SwiftUI preview, I have an app that runs clean architecture in multiple modules, SwiftUI preview doesn't work properly running the app scheme, so I had to run specifically the UI module, this works properly in most of the cases but sometimes injecting with `@LazyInjected` doesn't solve the issue and get the error ` resetAndTriggerFatalError("\(T.self) was not registered", #file, #line)`, I tried changing the build configuration to release for that module but for some reason the preview didn't work at all.

``` 
    public func promised<T>(key: StaticString = #function) -> Factory<T?>  {
        Factory<T?>(self, key: key) {
            #if DEBUG
            if self.manager.promiseTriggersError {
                resetAndTriggerFatalError("\(T.self) was not registered", #file, #line)
            } else {
                return nil
            }
            #else
            nil
            #endif
        }
    }
```

**Comment by hmlongco** [comment]
Would probably need a minimum viable project to try and diagnose this.

**Comment by callo90** [comment]
I'll prepare a quick demo.

**Comment by callo90** [comment]
**Demo**: 

This demo is a project using clean architecture with multiple modules, where each layer (Data, Domain, and Presentation) is separated into distinct modules. In this setup, the Presentation module is separated into a package, and the App module is responsible for injecting dependencies into the other modules.
https://github.com/callo90/factory-demo

**Problem**:
The error arises because the `promised<T>(key: StaticString = #function) -> Factory<T?>` doesn’t account for whether it's running the SwiftUI preview mode or not, which causes issues when injecting dependencies.

**Fix**:
I forked the project and fixed the error by adding a validation for preview mode with `FactoryContext.current.isPreview`. This ensures that dependencies are injected correctly when running previews.
https://github.com/callo90/factory
https://github.com/hmlongco/Factory/compare/main...callo90:Factory:main?expand=1

**Screenshots**:
Here are some screenshots that highlight the issue:

<img width="593" alt="Screenshot 2024-10-08 at 10 40 05 AM" src="https://github.com/user-attachments/assets/ad2309cd-786d-4d07-a22d-c280d89454ec">
<img width="427" alt="Screenshot 2024-10-08 at 10 40 10 AM" src="https://github.com/user-attachments/assets/343ac3fa-38e8-459c-b079-8968de7c5d50">

Let me know if you need anything else!

**Comment by callo90** [comment]
Hey @hmlongco did you have the chance to review this?

**Comment by hmlongco** [comment]
Preview Promise should be fixed in 2.4.0
```
private var _promiseTriggersError: Bool = FactoryContext.current.isDebug && !FactoryContext.current.isPreview
```

**Comment by callo90** [comment]
Great! Left this [PR](https://github.com/hmlongco/Factory/pull/251) with a similar approach

**Comment by Yondaimejab** [comment]
**Hello**

I also experienced the same issue, and after testing the fix in the version shared by @[callo90](https://github.com/callo90), it really seems to work. I want to thank you all for taking the time to address this issue. I’ll be testing version 2.4.0 to confirm if it resolves my problem completely.
Thanks again for your effort and support!
