### ISSUE TITLE
Is there a way to reset all containers in tests

### ISSUE THREAD

**Issue by tahirmt** [hmlongco/Factory#204]
Hi I have defined a number of custom containers and in my tests I want to call `.reset()` on all of them instead of remembering to add a line to reset every new container I end up creating later.

Is there a way to do this now?

**Comment by hmlongco** [comment]
No, but...
```swift
let containers: [ManagedContainer] = [c1, c2, c3, c6, c5, c4]
containers.forEach { $0.reset() }
```

**Comment by tahirmt** [comment]
Yeah that's kind of what I have now. It's just having to update this every time a new container is introduced.

**Comment by hmlongco** [comment]
Make each container autoRegistering and register with a global set.
