### ISSUE TITLE
Typo on Scopes.swift documentation

### ISSUE THREAD

**Issue by Kyle-Ye** [hmlongco/Factory#206]
https://github.com/hmlongco/Factory/blob/2729a04b17946f6e7f475395db1695caa94eaee2/Sources/Factory/Factory/Scopes.swift#L182

I guess it should be the following or something else.

```diff
- If no scope cache is specified then Factory is running in unique *more*.
+ If no scope cache is specified then Factory is running in unique *mode/scope*.
```

**Comment by hmlongco** [comment]
Fixed in upcoming update for 2.4.0
