### ISSUE TITLE
Async Init Support for Actors?

### ISSUE THREAD

**Issue by joeljfischer** [hmlongco/Factory#211]
I'm not sure how possible this would be, but it would vastly simplify some code that I'm moving into Actors for Swift 6 to allow it to use `init() async` and set up things like a `for await` loop directly within the initializer and eliminate possible data races by using `Task` in the initializer.

If it's not possible, then that's understandable, but it would be a great boon to using `actor` with `Factory` in certain use cases where things have to be set-up at initialization time.

**Comment by hmlongco** [comment]
Will peek, but doubt this will occur as I suspect it would require every step in the resolution chain (registration, caching, etc.) to also support async instances which would then mess with synchronous resolutions.

Might want to consider
```swift
struct AsyncInit {
    let a: Int
    init() async {
        a = 1
    }
}

struct AsyncInitWrapper<T> {
    let wrapped: () async -> T
}

extension Container {
    var someAsyncObject: Factory<AsyncInitWrapper<AsyncInit>> {
        self {
            AsyncInitWrapper { await AsyncInit() }
        }
    }
}

func test() {
    Task {
        let ai = await Container.shared.someAsyncObject().wrapped()
    }
}
```

**Comment by hmlongco** [comment]
As mentioned, it would require every step in the resolution chain (registration, caching, etc.) to also support async instances which would then mess with synchronous resolutions. Or half the supporting infrastructure would have to be cloned to support async factories.

Too many easy options available for the rare case in which you're want to do it, as shown earlier.
