### ISSUE TITLE
modular approach and scopes 

### ISSUE THREAD

**Issue by MartinP7r** [hmlongco/Factory#214]
Hi 👋🏼 

When using the modular approach you outlined in your [documentation](https://hmlongco.github.io/Factory/documentation/factory/modules#Wiring-Things-Together), how would one set a scope when actually registering the dependency inside the main app module?

```swift
extension Container: AutoRegistering {
    func autoRegister {
        accountLoader.register { AccountLoader() }
        ...
    }
}
```

I only found a way to use a default scope in that case, no per-dependency way of doing it.

```swift
extension Container: AutoRegistering {
    func autoRegister() {
        manager.defaultScope = .cached
        ...
    }
}
```

**Comment by hmlongco** [comment]
Try...
```swift
extension Container: AutoRegistering {
    func autoRegister {
        accountLoader
             .register { AccountLoader() }
             .scope(.cached)
        ...
    }
}
```

**Comment by MartinP7r** [comment]
thank you for the hint!
