### ISSUE TITLE
Swift 6 concurrency warnings

### ISSUE THREAD

**Issue by Lancelotbronner** [hmlongco/Factory#215]
Given containers like such on Factory `2.3.2`:

```swift
public final class CoreContainer: SharedContainer {
     public static let shared = CoreContainer()
     public let manager = ContainerManager()
}
```

With Swift 6 complete concurrency we get the following error `Class property 'shared' is not concurrency-safe because non-'Sendable' type 'CoreContainer' may have shared mutable state`.

Is Factory up-to-date with concurrency yet?

**Comment by hmlongco** [comment]
https://github.com/hmlongco/Factory/discussions/210

**Comment by NachoSoto** [comment]
Any plans to release a version that's compatible with Xcode 16?

**Comment by NachoSoto** [comment]
Also FYI that branch still doesn't solve the problem that `Factory` isn't Sendable, leading to errors like this:
```swift
enum Container {
  @MainActor
  static var instance: Factory<SomeType> {
    self {
      .init()
    }
  }
}

func someAsyncMethod() async {
  // Non-sendable type 'Factory<SomeType>' in implicitly asynchronous access to main actor-isolated property 'instance' cannot cross actor boundary
  let dependency = await Container.instance()
}
```

**Comment by hmlongco** [comment]
Assume you meant what??? 

```swift
extension Container {
  @MainActor var instance: Factory<SomeType> {
    self { .init() }
  }
}
```

Can't create static Factory's.

But check out the pinned issue on async Factory's. https://github.com/hmlongco/Factory/issues/211

Factory can't be Sendable without enforcing that T is Sendable, and..

a) Not every type will be Sendable
b) Enforcing Sendable would break a ton of existing code.

**Comment by NachoSoto** [comment]
Sorry that was a bad example. I did mean this inside Container.

How about:

```swift
extension Factory: Sendable where Element: Sendable {}
```

**Comment by NachoSoto** [comment]
Any plans to address this?
