### ISSUE TITLE
Registering a protocol with an associatedtype

### ISSUE THREAD

**Issue by fraserscottmorrison** [hmlongco/Factory#216]
Hiya, Ive been trying to register a protocol that has an associatedtype as a dependency, but I have compilation error. My project has various packages and Im using your modular development design. The following is a simplified example

In PackageB:
```swift
public protocol ModuleProtocol {
    associatedtype D: Codable
    func show(details: D) -> any View
}
```
Registering the dependency with the protocol. The compiler instructs me to use `any` due to associatedtype
```swift
extension Container {
    public var module: Factory<(any ModuleProtocol)?> { promised() }
}
```

In PackageA, which has PackageB as a dependency:
The class that adheres to ModuleProtocol
```swift
public final class Module: ModuleProtocol {
    public typealias D = Details
    
    public func show(details: Details) -> any View {
        DetailsView(details: details)
    }
}
struct Details: Codable {}
```
Auto register the module class
```swift
extension Container: AutoRegistering {
    public func autoRegister() {
        module.register { Module() }
    }
}
```
Lastly, here I want to instantiate the dependency
```swift
if let module = Container.shared.module() {
    module.show(account: account) // compilation error here
}
```
I have a compilation error when trying to call the function of the instance
`Member 'show' cannot be used on value of type 'any ModuleProtocol'; consider using a generic constraint instead`

Perhaps my knowlegde of swift generics is letting me down here. Do you know how I can avoid this error?

**Comment by hmlongco** [comment]
Can't do that with associated types, generics won't allow it.

**Comment by fraserscottmorrison** [comment]
Is it possible to register a protocol with associated types with Factory in another way?

**Comment by wazawoo** [comment]
I would like to get a better understanding of how to handle this.

Does it mean we cannot use protocols with associated types at all with Factory?

If that's the case, are these the only solutions?
1. Don't use protocols with associated types
2. Change the protocols to use generic constraints instead

For context, I just want to use Factory for some services used across the app (not trying to use it for viewModels). These services have associated types.

**Comment by hmlongco** [comment]
If you define your associated type as follows...
```swift
protocol AsyncRequest<T>: Sendable {
    associatedtype T: Sendable
    func callAsFunction() async throws -> T
}
```
Then you can define your Factory as...
```swift
extension Container {
    var requestUsers: Factory<any AsyncRequest<[User]>> {
        self { RequestUsers() }
    }
}
```
Example of that's at the following link...

https://medium.com/p/a5bb93641609

You'd have the same issue writing a function to return `any ModuleProtocol`. There's no type information available for Swift to determine the actual associated type (D). The parameter show(details: x) is expecting could be an Account or an Int. Swift has no way of knowing.

**Comment by wazawoo** [comment]
Thanks so much!

I was running into problems because I was using a different generic type for production / mock versions of a service. So It wasn't clear how I could register both of those.

I'll check out the article (that's what I'm trying to accomplish anyways)
