### ISSUE TITLE
Resolvers .implements?

### ISSUE THREAD

**Issue by mszyszylo** [hmlongco/Factory#22]
Hello Mr. Long,

i love the work you did with Resolver and now Factory and am trying to refactor my project.
I stumbled into one problem that Resolver solved for me.

Resolvers: 
`
    @discardableResult
    public func implements<Protocol>(_ type: Protocol.Type, name: Resolver.Name? = nil) -> ResolverOptions<Service> {
        registration.resolver?.register(type.self, name: name) { r, args in r.resolve(Service.self, args: args) as? Protocol }
        return self
    }`

is missing on Factory and plays a huge part of our architecture which is sliced into several frameworks that need to use the same object based on their own protocol implementations.

E.g. 
`register  { AuthenticationClass() }.implements(AuthenticationProtocol.self).implements(LoginProtocol.self)`

Where “AuthenticationProtocol” sits on another framework as “LoginProtocol”.

I didn’t find a solution for Factory that would serve us without exhibiting the real “AuthenticationClass” to both of them yet.

Greetings Michael S.

**Comment by hmlongco** [comment]
How about...
```swift
public protocol AServiceType {
    func text() -> String
}

public protocol BServiceType {
    func text() -> String
}

class Multiple: AServiceType, BServiceType {
    func text() -> String {
        return "Multiple"
    }
}

extension Container {
    private static var multiple = Factory<AServiceType&BServiceType> { Multiple() }
    static var aService = Factory<AServiceType> { multiple() }
    static var bService = Factory<BServiceType> { multiple() }
}

class MultipleDemo {
    var aService: AServiceType = Container.aService()
    var bService: BServiceType = Container.bService()
}
```
Then again, since it's private you could simply do without the types...
```swift
extension Container {
    private static var multiple = Factory { Multiple() }
    static var aService = Factory<AServiceType> { multiple() }
    static var bService = Factory<BServiceType> { multiple() }
}
```
