### ISSUE TITLE
MainActor isolated depenedencies

### ISSUE THREAD

**Issue by tareksabry1337** [hmlongco/Factory#224]
First of all thank you for the huge amount of work put in Factory / Resolver I have been using your tools since they came out and I truly like them.

Is there any possibility to fix what's shown below? `DeepLinkHandlerCoordinator` is marked as @MainActor and obviously all the resolving is not @MainActor, which means we can't use .init() inside resolution closures, but these specific classes can't be not marked as @MainActor as well.

<img width="1264" alt="Screenshot 2024-09-04 at 08 00 28" src="https://github.com/user-attachments/assets/e497af83-f957-4dec-932c-2d681c31eeeb">

**Comment by tareksabry1337** [comment]
Read through other issues, it looks like there is no way around this currently

**Comment by hmlongco** [comment]
Did you read this?

https://github.com/hmlongco/Factory/issues/135

**Comment by tareksabry1337** [comment]
Yes, that is why I closed this and I have a PR that addressed this behavior

**Comment by Carrione** [comment]
What if we need to use an instance of the main-isolated class, like UIApplication.shared? Is there any solution for this situation?

**Comment by hmlongco** [comment]
@tareksabry1337 So the branch is fixing the problems for you?

**Comment by tareksabry1337** [comment]
@hmlongco Yes, works as intended!

**Comment by PhiFry** [comment]
> [@Carrione](https://github.com/Carrione) https://github.com/hmlongco/Factory/tree/concurrency This branch fixes this issue and allows you to use MainActor bound dependencies freely.

Where is this branch now? It seems to be removed and branch swift6 hasnt had a new commit since september.

**Comment by hmlongco** [comment]
Merged into main.
