### ISSUE TITLE
Xcode 15.2 compatibility

### ISSUE THREAD

**Issue by masterchiip** [hmlongco/Factory#239]
Hi team, I'm exploring your library and noticed that with Xcode 15.2 I can't build the demo project using **v2.4.0**.
I'm getting many compiler errors like this one.
![image](https://github.com/user-attachments/assets/028dadc6-b6f1-459e-883e-f7835aa915dd)

With **v2.3.2** I was able to compile.

**Comment by bweissmann** [comment]
+1
We got the same errors on our build pipeline (MS AppCenter, Xcode 15.0.1 Preview).
Locking our version of Factory to <2.4.0 until resolved 🙂

**Comment by hmlongco** [comment]
Not sure these *will* be resolved. 2.4 is Xcode 16 support.

**Comment by bweissmann** [comment]
Thank you for the clarification, I can report that upgrading our build pipeline to Xcode 16 with Factory 2.4.0 has resolved our issue.

**Comment by masterchiip** [comment]
Any ideas how this could be fixed @hmlongco ? I could help with exploring the fix.

**Comment by hmlongco** [comment]
Not without going and conditionalizing a bunch of code and I'm not sure what the point of that would be. If you need Xcode 15 support cap the version at 2.3.x. In about five or six months you're going to have to move to Xcode 16 anyway.

**Comment by philippelesaux** [comment]
The minimum Swift version should probably be bumped, then, since the Swift 5.9 compiler is not compatible with the source in >= 2.4

https://github.com/hmlongco/Factory/blob/main/Package.swift#L1
