### ISSUE TITLE
What is best way to DI in this situation? 

### ISSUE THREAD

**Issue by sanghun0724** [hmlongco/Factory#25]
Hello. i'm newbie in factory 
now I'm trying to put factory in my project 
but i'm little hard to construct DI Architecture 
So.. can i get some advice on this? 

 ----------- MY SITUATION --------------
 E.x) before (factory)
if i create new viewController instance ..
```swift
 let myRecordViewController = MyRecordViewController(viewModel: MyRecordViewModel(usecase: RecordsUseCase(recordsRepository: RecordsRepositoryImpl(recordAPI: RecordAPI()))))
```
--> my core VC count is 5 (home, record, search, dj, profile)
 E.x) after (add factory)
so.. now i'm trying .. 
```swift 
import Factory
import Alamofire

extension SharedContainer {
    static let defaultSession = Session.default
}
```
seperate container (home, record, search, dj, profile) like this
```swift 
class RecordContainer: SharedContainer {
    static let recordVC = Factory<MyRecordViewController> {
        MyRecordViewController(viewModel: MyRecordViewModel(usecase: RecordsUseCase(recordsRepository: RecordsRepositoryImpl(recordAPI: RecordAPI(session: defaultSession)))))
    }
}
```
What is best way to Di in this situation? 
Am I going the right way? 
Thank you!

**Comment by hmlongco** [comment]
You want to break things down into individual components.
```swift
class RecordContainer: SharedContainer {
    static let recordAPI = Factory { RecordAPI(session: defaultSession) }
    static let recordsRepository = Factory<RecordsRepository> { RecordsRepositoryImpl(recordAPI: recordAPI()) }
    static let recordsUseCase = Factory { RecordsUseCase(recordsRepository: recordsRepository()) }
    static let recordsViewModel = Factory { MyRecordViewModel(usecase: recordsUseCase()) }
}
```
I noted that you had a RecordsRepositoryImpl which implied a RecordsRepository protocol. Generally you don't need to add an explicit type unless you have a protocol and you're planning on mocking it for previews or testing.

I also generally wouldn't use Factory for views and view controllers.
```swift
class MyRecordViewController: UIViewController {
    @Injected(RecordContainer.recordsViewModel) var viewModel
}

func launch() {
    let vc = MyRecordViewController()
    pushViewController(vc, animated: true)
}
```
Finally, breaking things down into individual components lets you reach in and alter the behavior of the system by changing dependencies prior to instantiating the class.
```swift
func test() {
    RecordContainer.recordsRepository.register { RecordsRepositoryMockNoRecords() }
    let vm = RecordContainer.recordsViewModel()
    vm.load()
    XCTAssert(vm.numberOfRecords == 0)
}
```

**Comment by sanghun0724** [comment]
wow.. Thank you @@ 
I will try refactoring according to your explanation
