### ISSUE TITLE
I can't register new instance 

### ISSUE THREAD

**Issue by sanghun0724** [hmlongco/Factory#28]
Hi @hmlongco 
I'm big fan of Factory 
but i face some problem now (title)
It would really help me if I could take your advice.

My situation is .. 

-- Container  -- 

```swift 
extension Container {
    static var notificationUsecase = Factory<ReserveNotificationUsecase> { ReserveService() }
}


extension Container {
    static func setupMocks() {
        notificationUsecase.register(factory: { ReserveStubService() })
    }
}
```

-- ViewModel -- 
```swift 
extension ReserveViewModel {
 struct Dependency {
        @Injected(Container.notificationUsecase) var notificationUsecase
    }

    private func viewModelSomeFunc() {  // this is called after init() 3 seconds
        Container.setupMocks() // <- register Stub here!! but .. 
        LogUtil.d(dependency.notificationUsecase) // ReserveService   <--- WRONG <---- (I want this part is defined as ReserveStubService )
        LogUtil.d(Container.notificationUsecase.callAsFunction()) // ReserveStubService <--- OK 
}
```

_**@Injected Instance != Container Instance**_ 

I tried for five hours, but it didn't work.. 
https://github.com/hmlongco/Builder
I  also tried to refer to this demo app, but it failed
What did I miss?

++)
-- my debugging range --
<img width="761" alt="Screen Shot 2022-10-08 at 6 00 03 PM" src="https://user-images.githubusercontent.com/66512239/194699381-d7ab1e7c-61b7-4a51-91dc-92aa4e480c1f.png">

I don't know where to go from here.
Thanks

**Comment by sanghun0724** [comment]
Oh my god... 
 i was trying to `Container.setupMocks` 
 it works!!! 
-> **_I think it was the point of time issue of calling the function._**
I will leave an issue for those who will have problems like me later.

**Comment by hmlongco** [comment]
Sorry, took awhile to get to this. Yeah, can't tell where, but at some point in the code Dependency was created before viewModelSomeFunc() was called. As such Dependency was created with the original value as @Injected resolves immediately.
