### ISSUE TITLE
Factory vs EnvironmentObject

### ISSUE THREAD

**Issue by abegehr** [hmlongco/Factory#31]
Hey @hmlongco, thank you for publishing Factory and all your open source work in the Swift/iOS community!
I'm working on a SwiftUI project for which we've been using singletons for services so far. It's gaining complexity now, so I'm looking at a better option for dependency injection. Reading through the Factory readme, I'm wondering in which cases to go with a Factory-injected service and when to use a vanilla EnvironmentObject. Do you have any pointers that can help with this decision?

**Comment by hmlongco** [comment]
Many of my more complex views in SwiftUI look similar to the following pattern...

```swift
class SomeViewModel: ObservableObject {
    @Injected(Container. textLoadService) var textLoadService
    @Published var text: String = ""
    @MainActor
    func load(id: String) async {
        text = await textLoadService.load(id: id)
    }
}

struct SomeView: View {
    let id: String
    @StateObject var viewModel = SomeViewModel()
    var body: some View {
        Text(viewModel.text)
            .task {
                await viewModel.load(id: id)
            }
    }
}
```

I use Factory to provide services to the ViewModel for the views that have them. (Or to provide dependencies for the services, in this case TextLoadService would probably have its own dependency on a network service.)

I have quite a few articles on Medium that pertain to this, check out: https://betterprogramming.pub/swiftui-view-models-are-not-protocols-8c415c0325b1

In fact, you might look at the entire SwiftUI series.

This help?

**Comment by abegehr** [comment]
Awesome, thanks you for sharing the pattern and link to your Medium, @hmlongco! 
Reading through the articles, the main problems I see with using an EnvironmentObject (instead of a Factory) as (micro)services are:
- EnvironmentObjects are not passed to sheets (new view hierarchies): https://medium.com/swlh/swiftui-and-the-missing-environment-object-1a4bf8913ba7
- ObservableObjects can't depend on each other, making it harder to split out services to achieve high cohesion (loose coupling and high cohesion [are goals for SoC](https://nalexn.github.io/separation-of-concerns/?utm_source=nalexn_github))
