### ISSUE TITLE
Container or SharedContainer

### ISSUE THREAD

**Issue by paul-lavoine** [hmlongco/Factory#33]
Hello Sir,

I have a simple question about the Container class, because I didn't understand what is the real interest of this one ?

We can already use **SharedContainer** or we can create **our own container** with the SharedContainer inheritance. Both make definitely sense.

Then I opened the Factory.swift:
`public class Container: SharedContainer { }`

So why did you create this Container class ? What is the difference with create our own container ?
I supposed it just a default container for user. Is it right ?

Thanks,
Paul

**Comment by hmlongco** [comment]
Container is the default and suitable for most cases. You can also create your own containers/namespaces. If you do so, they  should derive from SharedContainer. 

But SharedContainer can also be used, with the understanding that anything put there is visible to all containers.

**Comment by paul-lavoine** [comment]
thanks
