### ISSUE TITLE
Injected does not use a newly registered dependency

### ISSUE THREAD

**Issue by samwize** [hmlongco/Factory#35]
I was expecting `@Injected` to use a dependency that I registered in my unit test, but turns out it depends on when the mocking code is called. I believe it is similar to this #28.

The implementation of `Injected` is not what was expected. It stores the dependency on initialization, which means if we register a factory later, it won't use the new factory. Shouldn't it store the factory instead?

I make the desired behaviour in my fork https://github.com/hmlongco/Factory/commit/ca2b0dc3eec8ec8b18e12fc01abefc0b9421c45b

**Comment by hmlongco** [comment]
That's expected (and desired) behavior. All @Injected dependency properties are resolved on initialization of the parent object so they're immediately ready for use. 

If you're into delayed gratification you can use @LazyInjected (assuming, of course, that you're doing so in a class/reference type as @LazyInjected is mutable).

**Comment by samwize** [comment]
Gotcha. Thank you for the explanation and confirmation of how it is designed.
