### ISSUE TITLE
SharedContainer Resolve

### ISSUE THREAD

**Issue by joaoGMPereira** [hmlongco/Factory#36]
Hey @hmlongco! I was thinking in a way to resolve a Factory passing a type something like that:
```swift
open class SharedContainer {

    public static func resolve<T>(scope: Scope) -> T? {
        resolveRegistration() ?? resolveScope(scope: scope)
    }
    
    static func resolveRegistration<T>() -> T? {
        let factories: [T] = Container.Registrations.registrations.compactMap { key, factory in
            guard let currentFactory: T = (SharedContainer.Registrations.factory(for: key) as? TypedFactory<Void, T>)?.factory(()) else {
                return nil
            }
            return currentFactory
        }
        return factories.first
    }
    
    static func resolveScope<T>(scope: Scope) -> T? {
        scope.cache.compactMap { id, factory in
            factory.instance as? T
        }.first
    }
 }
```
    
  Do you think that this could be a way to do that? Or im not thinking in something?

**Comment by hmlongco** [comment]
Factories don't register their default closures. If you think about it you'll see that Swift doesn't provide a mechanism for that to occur, since the static variable containing them is evaluated lazily. They don't exist until accessed, and by then... too late.

SharedContainer Registrations only exist for factories that are re-registered at a later point in time.
```swift
Container.myFactory.register { MyObject() }
```

**Comment by joaoGMPereira** [comment]
I was testing this solution to find the correct object even when a register occurs over closure of Factory or the cached object of that type for expecific scope.

I was thinking on that because in my company we have hundreds of Module and Interface Module, and for example:

FirstModule have 1 factory:

```swift
static var firstModuleObject = Factory<[ModuleObjectInterface]>(scope: .cached) { ModuleObject() }
```

And in second module I wanna know about just the interface like:
```swift
static var firstModuleObject: ModuleObjectInterface = SharedContainer.resolve(scope: .cached)
```

because Second Module, will not know about firstModuleObject that will be in concrete module of FirstModule, but knows about FirstModuleInterface and Factory, got it?

**Comment by hmlongco** [comment]
Read the section on Optionals and Dynamic Registration in the docs. Unfortunately you're going to need call some function in a bunch of modules so they can do their own registrations Resolver-style. 

This was discussed a bit in https://github.com/hmlongco/Factory/issues/26

**Comment by joaoGMPereira** [comment]
Thanks for answer, was what I was looking for thanks!

**Comment by Christopher-A** [comment]
Do you have any recommendations as to where to call the modules to register its implementations? For a normal application, AppDelegate.init() works fine, but with SwiftUI Previews, this doesn't get called.

**Comment by hmlongco** [comment]
Download the current branch

**Comment by hmlongco** [comment]
Download the current main branch and then put something like the following in your code.

```swift
import Factory

extension Container: AutoRegistring {

    static let autoRegisteredService = Factory<MyServiceType?> {
        nil
    }

    public static func registerAllServices() {
        autoRegisteredService.register {
            MyService()
        }
    }

}
```
This is similar to Resolver's mechanism where registerAllServices() will be called prior to the very first resolution. Put any needed registrations here, or call out to modules to perform their own.

**Comment by Christopher-A** [comment]
Awesome- Thank you!
