### ISSUE TITLE
Question about Dynamic Registration example

### ISSUE THREAD

**Issue by totidev** [hmlongco/Factory#4]
```swift
func authenticated(with user: User) {
    ...
    Container.userProviding.register { UserProvider(user: user) }
    ...
}
```
In the above example that you provide, what was the way that `userProviding` was initially registered? Should this be created as a nilable, a UserProvider that takes no user, or even a separate type conforming to `UserProviding` protocol?

**Comment by hmlongco** [comment]
Considering that I made up the example... ;)

Let's go with the optional protocol version.
```swift
extension Container {
    static let userProviding = Factory<UserProviding?> { nil }
}
```

**Comment by hmlongco** [comment]
And just to round out the example...
```swift
func logout() {
    ...
    Container.userProviding.register { nil }
    ...
}
```

**Comment by totidev** [comment]
Thanks for this. 
Would a better approach be to create a custom scope for authenticated users, and then reset this?

Also, following the guide you provided, it would seem that calling:
```swift
Container.userProviding.reset()
```
Should also set it back to nil, if I have understood it correctly.

**Comment by totidev** [comment]
Thanks for this. 
Would a better approach be to create a custom scope for authenticated users, and then reset this?

Also, following the guide you provided, it would seem that calling:
```swift
Container. userProviding.reset()
```
Should also set it back to nil, if I have understood it correctly.

**Comment by hmlongco** [comment]
That was primarily an example I made up to show how you could change behavior during runtime. I wouldn't read too much into it from an architectural standpoint.

That said, I've done the session scope thing in several apps.

And yes, gold star! Reset would work as well.
