### ISSUE TITLE
callAsFunction build error undefined symbol

### ISSUE THREAD

**Issue by doozMen** [hmlongco/Factory#40]
I'm using factory in a library inside a swift package. It works well. Only problem is on when using it inside a framework it cannot find the symbol call as function.

I get this error

```
Undefined symbols for architecture x86_64:
  "_$s7FactoryAAV14callAsFunctionxyF", referenced from:
      _$s11ChameleonUI12ThemeManagerC17pageControlConfigAC04PagefG0VvgAFyXEfU_ in ThemeManager.o
  "_$s7FactoryAAVMn", referenced from:
      _symbolic _____y_____G 7FactoryAAV 9Chameleon5ColorV in ThemeManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have no clue why this happens. Do you?

**Comment by hmlongco** [comment]
Haven't seen it. Might check this...

https://stackoverflow.com/questions/18408531/xcode-build-failure-undefined-symbols-for-architecture-x86-64

**Comment by doozMen** [comment]
We have indeed many problems with this related to x86 architecture and pods. Probably not related to factory so I will close this issue. Thanks for the response and awsome open source project!

We will be using it at [Mediahuis](https://www.mediahuis.be/nl/) to inject brand specific stuff in all our brands! Thanks for that!
