### ISSUE TITLE
Getting structured concurrency warning when using property wrappers

### ISSUE THREAD

**Issue by lukacs-m** [hmlongco/Factory#41]
Hello,

I have recently been working on a project where I switched the `Stricted concurrency checking` too `complete`.
After doing that I end up with several concurrency warning for `@Injected` variables.

```swift
final class GetCurrentLyrics: GetCurrentLyricsUseCase, Sendable {
    //// Warning on this variable
    @Injected(UseCasesContainer.getCurrentMedia) private var getCurrentMedia: GetCurrentMediaUseCase

   xxxxxx rest of code
}
```

The `@Injected` variable produces the following warning: `Stored property '_getCurrentMedia' of 'Sendable'-conforming class 'GetCurrentLyrics' is mutable`. Could there be a way to remove this warning ?

Never the less thank you very much for this wonderful tool that is Factory.

**Comment by hmlongco** [comment]
Did you try it w/o the property wrapper?

```swift
private let getCurrentMedia = UseCasesContainer.getCurrentMedia()
```

**Comment by lukacs-m** [comment]
As of now no :)
But will do :)
