### ISSUE TITLE
Shared scope tests failed under iOS 13.7 

### ISSUE THREAD

**Issue by ernesto** [hmlongco/Factory#43]
v1.2.9

When run unit tests using iOS 13.7, the tests **testProtocolSharedScope** and **testExplicitProtocolSharedScope** fails. The same functions pass with success with iOS 15 .

Both fails when running this assert function: XCTAssertTrue(service1?.id == service2?.id)

I think it will always create a new instance when using iOS 13, even using shared scope.

**Comment by hmlongco** [comment]
Looks to be the same in iOS 14. Think I have a fix. Try switching to the "graph" branch, pull it, and see if things are better. (Testing a new feature there.)

**Comment by hmlongco** [comment]
Should be fixed in 1.3.0.
