### ISSUE TITLE
Cached vs Singleton scope, what's the difference?

### ISSUE THREAD

**Issue by lm2s** [hmlongco/Factory#44]
Hello.
I'm having a hard time understanding the difference between the cached and singleton scopes.
Both will keep one instance of an object in memory and return that instance to the caller and both scopes have the reset functionality (`Scope.cached.reset()` and` Scope.singleton.reset()`). 
Which leaves me a bit confused about the differences between the two.

**Comment by hmlongco** [comment]
Basically the difference is intent. Singletons are meant to last the lifetime of the app, while anything cached could be released at any point in time. (new user session, etc.)

Singletons are protected by default from a global cache reset. That said, they have the capability to be reset, useful when running unit tests.

**Comment by lm2s** [comment]
Got it! Thank you for the clarification.
