### ISSUE TITLE
UITest sample

### ISSUE THREAD

**Issue by mehdok** [hmlongco/Factory#45]
Hi,
Could you please provide a sample for **UI** tests and registering mocks?

related issues:
[TestUnit: I can't register](https://github.com/hmlongco/Factory/issues/34)
[I can't register new instance](https://github.com/hmlongco/Factory/issues/28)

**Comment by hmlongco** [comment]
The test case is fairly straightforward...
```swift
import XCTest

final class FactoryDemoUITests: XCTestCase {
    func testExample() throws {
        let app = XCUIApplication()
        app.launchArguments.append("-mock1")
        app.launch()

        let welcome = app.staticTexts["Mock Number 1! for Michael"]
        XCTAssert(welcome.exists)
    }
}
```
And then in the application make `Container` conform to `AutoRegistering` so we can can get in before everything kicks off and change anything we need to suit.
```swift
import Foundation
import Factory

#if DEBUG
extension Container: AutoRegistering {
    public static func registerAllServices() {
        if ProcessInfo().arguments.contains("-mock1") {
            myServiceType.register { MockServiceN(1) }
        }
    }
}
#endif
```
Obviously, one can add as many different test cases and registrations as needed.

**Comment by Mehdi-Sohrabi0** [comment]
Perfect, Thank you.
