### ISSUE TITLE
Determine scope for optional registration

### ISSUE THREAD

**Issue by mb4lazs** [hmlongco/Factory#48]
I would like to use injection among modules. Let's say a module depends on other module's interface module which contains protocol definition. Beside that interface I would like to place the factory of the optional type as well. 
In this case how can I define the scope at the explicit register() call for example in a third (main) module where only that module should know about the lifecycle? So the scope definition could remain always at the place of the actual registration.

**Comment by hmlongco** [comment]
See if this helps: https://betterprogramming.pub/factory-multiple-module-registration-f9d19721a31d?sk=a03d78484d8c351762306ff00a8be67c

**Comment by mb4lazs** [comment]
Great article, thank you! Is it possible to set the scope also in the autoRegistration part to control the lifecycle in a different module than the factory exists (ModuleA)? Like this:

```
extension Container: AutoRegistering {
   static func registerAllServices {
     accountLoader.register(scope: .session) {AccountLoader() }
   }
}
```

**Comment by hmlongco** [comment]
The scope can't be changed as the Factory is immutable once created. Registrations are stored in a common pool.
