### ISSUE TITLE
ParameterService Question

### ISSUE THREAD

**Issue by rydamckinney** [hmlongco/Factory#49]
Hi there! This is a phenomenal library. I've integrated it extensively for a complex cross-platform commmunications app. A few questions:
- Is there a way to dynamically create `Scopes` at runtime? Or is compile-time definition a fixed constraint?
- For the `ParameterService` -- are the objects that are _created by_ the factory callback cached at the DI layer? Or is it just the factory that is cached? For example -- if I wanted to use a `ParameterService` registration for a factory that creates arbitrary view models, initialized w/provided parameters -- are those objects cached? For the N+1 occurence that a given `ParameterService` receives the same parameters, is the previously-produced object (returned in the factory callback) returned?

**Comment by hmlongco** [comment]
Never tried it. The scope is set in the static's lazy initializer so I'm not sure how you'd change it. Ummm... you could try using a variable on the initializer but seems a bit clunky. Note that once a given Factory has been resolved for the first time there's no way to change the scope afterwards.

Scopes cache the created objects, so if a parameterized object was cached you'd get a service with whatever the value was previously. If no scope was specified then you get a unique object with the current parameter.

Glad you're enjoying the library. If you're up to a little quid pro quo, I have a couple of things I'd like an opinion on in regard to future directions...

**Comment by hmlongco** [comment]
https://github.com/hmlongco/Factory/issues/51
