### ISSUE TITLE
Initialize services with @MainActor property wrapper

### ISSUE THREAD

**Issue by lumo2707** [hmlongco/Factory#5]
Hi, I have the following issues regarding initalizing a service which should execute its code on main thread.

So I have a service call LoginService:

`
@MainActor
internal final class LoginService: ObservableObject  {
@MainActor
internal func login(to route: MainRoute) {}
}`

But when I try to inialize this service i got the following compiler error:

` static let loginService = Factory {
        LoginService() as LoginServiceProtocol
    }`

--> Call to main actor-isolated initializer 'init()' in a synchronous nonisolated context`

How should I handle this? Should I only add "MainActor" property wrapper to the functions instead of the whole object?

Thanks in advance.

**Comment by lukasz-szyszkowski** [comment]
Your problem is out of the scope of this project, for more info about `@MainActor` I recommend this article https://www.hackingwithswift.com/quick-start/concurrency/how-to-use-mainactor-to-run-code-on-the-main-queue

**Comment by hmlongco** [comment]
That was an issue in Resolver as well. My suggestion is yes, only add the mainActor *attribute* to the function(s) that need it.

See: https://github.com/hmlongco/Resolver/issues/150
