### ISSUE TITLE
Can't install Factory over Cocoapods for WatchOS Target

### ISSUE THREAD

**Issue by hschaeufler** [hmlongco/Factory#54]
When I add the Factory-Package to my Podfile and run `pod install` i get following message:
```
Analyzing dependencies
[!] The platform of the target `Watch App` (watchOS 9.1) is not compatible with `Factory (1.3.5)`, which does not support `watchOS`.
```

This is the podfile:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Watch App' do
  platform :watchos, '9.1'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Factory', '~> 1.3.5'
```

Am I doing something wrong?

The Package.Swift-File for the Swift Package Manager states that `.watchOS(.v6)` is also supported.

Best regards

Holger

**Comment by hmlongco** [comment]
It's in the SPM but I don't think watch os is in the podspec. Will need to check.

**Comment by hschaeufler** [comment]
> It's in the SPM but I don't think watch os is in the podspec. Will need to check.
Thank you for the quick reply. As a workaround, I could include it via SPM and use it for WatchOS. It would also be cool if this were possible via Cocoapods. Since my project is integrated into a Flutter project and Cocoapods are currently still used there.

**Comment by hmlongco** [comment]
I tried adding watchOS and got errors I don't have time to track at the moment. Sorry.

**Comment by hschaeufler** [comment]
Thanks anyway for trying it out.  👍

**Comment by hmlongco** [comment]
I updated the pod spec. The only way I could get it to build, however, was by setting the minimum deployment target to 8.2

  s.watchos.deployment_target = "8.2"
  s.watchos.framework  = 'SwiftUI'

This was on Xcode 14.2.
