### ISSUE TITLE
Reset session

### ISSUE THREAD

**Issue by gamble2020** [hmlongco/Factory#56]
Hi,

I'm trying to reset a cached registration using the .session example for a user account that is obtained via MSAL. When I try to reset it in my logout handler the state isn't being updated in my swift ui Auth view. Am I doing something wrong? The view is using an EnvironmentObject for reference.

Cheers

Simon

**Comment by hmlongco** [comment]
Reseting the cache means that the **next** time Factory is asked for an object it will get brand new objects and not a previously cached version. Reseting the cache doesn't change anything that's already been resolved.

If you do the following...
```swift
var cached: ABC? = ABC()
var abc = cached
cached = nil
```
The reference to the object in `abc` still exists even though the cached variable was "reset".
