### ISSUE TITLE
Closure factories compile ok but get tagged with errors by Xcode 

### ISSUE THREAD

**Issue by drekka** [hmlongco/Factory#89]
So I have the following code where I'm using Factory to return a closure instead of a type:

```swift

public func factory() -> Container {
    Container.shared
}

public typealias DateProviding = () -> Date

public extension Container {
    var dateProvider: Factory<DateProviding> { self { { Date() } } }
}


// And later in some code...
factory().dateProvider()() 
```

This compiles successfully however Xcode then goes an tags it with an error even though there isn't one:

<img width="684" alt="Screenshot 2023-03-30 at 17 10 30" src="https://user-images.githubusercontent.com/153837/228745229-9f969a4b-e7ec-47e3-8bf4-bba1c70b849c.png">

It looks likes Xcode is miss-interpreting this code even though it compiles fine. I've tried

```swift
(factory().dateProvider)()() 
(factory().dateProvider())()
let x = factory().dateProvider()
x() 
```

But they all trigger the error. So far it looks like the only thing that removes it is if I do this:

```swift
let x:() -> Date = factory().dateProvider()
x() 
```

Any thoughts on how to get Xcode to behave?

**Comment by hmlongco** [comment]
I dropped this into the factory demo and ran it with no issues.
```swift
public func factory() -> Container {
    Container.shared
}

public typealias DateProviding = () -> Date

public extension Container {
    var dateProvider: Factory<DateProviding> { self { { Date() } } }
}

func test() {
    // And later in some code...
    let date = factory().dateProvider()()
    print(date)
}
```
The problem is probably somewhere in the code you didn't post. You're masking factory or Container with some locally defined name.

**Comment by drekka** [comment]
Hmm. Ok. Let me dig into that bit more :-)

**Comment by drekka** [comment]
Ok, my bad. Looks like some subtle missing imports and missing dependency references in a package file. The compiler was still able to find everything through transient dependencies and the likes, but XCode was flagging the errors when it was compiling for code completion. Which explains why it would compile and run fine, then a few seconds later Xcode would flag an error. Anyway, adding the imports and missing dependencies and it all appears to be good now.

Thanks for taking the time to double check :-)
