### ISSUE TITLE
Xcode complaining to force cast when factory object passed as argument in container

### ISSUE THREAD

**Issue by mahabaleshwarhnr** [hmlongco/Factory#91]
Hi I am exploring Factory 2.1.0. I am using constructor DI method. I am using Xcode 14.1 and swift 5.7. I cannot use Factory type in constructor as mentioned in the doc. Xcode complaining to do force downcast. I have to use `resolve()` to fix this problem.
My container looks like this:

```
extension Container {
    var blogPostRepository: Factory<BlogPostsRepository> { self { BlogPostsRepositoryImpl(apiClient: self.apiClient) } }
}

extension Container {
    
    var blogListViewModel: Factory<BlogListViewModel> {
        Factory(self) {
            BlogListViewModel(repository: self.blogPostRepository.resolve(), mainScheduler: self.mainScheduler.resolve())
        }
    }
}
```
Error Screenshot:

<img width="1288" alt="Screenshot 2023-03-30 at 6 15 58 PM" src="https://user-images.githubusercontent.com/11162668/228840738-dbc3fb22-fb0c-43cd-b211-87fbdbdce522.png">

**Comment by hmlongco** [comment]
You need to resolve the factory for `self.apiClient()` (add parens)
```swift
extension Container {
    var blogPostRepository: Factory<BlogPostsRepository> { self { BlogPostsRepositoryImpl(apiClient: self.apiClient()) }  }
}
```
